---
title: "Running tutorials"
format:
    html:
        toc: true
        code-fold: true
---

# Tutorial program

```{r workshop-program}
#| echo: false
library(tibble)
library(kableExtra)
timetable <- tribble(
    ~"Time", ~"Stream 1", ~"Stream 2", ~"Stream 3", ~"Stream 4",
    "AM", "Data Visualisation (Emi)", "Version Control (Patricia?)", "Introduction to optimization with Python (Jess)", "Wrangling spatio-temporal data (Sherry)",
    "PM", "Shiny (Mitch)", "Forecasting (Rob)", "Bayesian Inference and regression using Stan (Lauren)", "Visual mapping of natural disasters (Kate)"
)

kable(timetable) |>
    kable_styling(latex_options = "striped")

```

# Blurbs

## Lauren

### Getting started with Bayesian inference with brms and Stan

In this workshop, Lauren will work through the steps of Bayesian Workflow using brms (and Stan). We will cover how to select a prior using prior predictive checks, understand the model diagnostics, perform model checking using posterior predictive checks and leave-one-out cross-validation.

## Emi

### Effective Data Visualisation with R

In this 3 hour tutorial, I will demonstrate some cognitive principles and apply methods supported by empirical studies that make data visualisation more effective. The construction of data visualisation will be accompanied with R code using the ggplot2 package. The R code and data used will be provided so participants can fully replicate the presented data visualisations.
Participants are expected to know how to use R. Some knowledge in tidyverse would be beneficial. You can find an interactive introduction to data analysis with R at https://learnr.numbat.space/.

### Biography

Dr. Emi Tanaka is a Senior Lecturer in Statistics at Monash University whose primary interest is to develop impactful statistical methods and tools that can readily be used by practitioners. Her research area includes data visualisation, mixed models and experimental designs, motivated primarily by problems in bioinformatics and agricultural sciences. She is currently the President of the Statistical Society of Australia Victorian Branch and the recipient of the Distinguished Presenter's Award from the Statistical Society of Australia for her delivery of a wide-range of R workshops.

## Kate

### Spatio-temporal visualisation for natural disasters

In this tutorial, we'll use spatio-temporal data to visualise weather forecasts and other related natural disaster predictions for the purposes of understanding and communicating risk. We will learn how to create visualisations in both space (extent mapping) and time (forecast trajectories) using best practice principles. We will also explore how to incorporate uncertainty into our visualisations.

## Jess

### Optimization in Python and its application in carbon portfolio

This workshop provides an introduction to mathematical optimization with Python implementations. We will work on a carbon portfolio model, which is an analytical framework for evaluating investment opportunities and maximizing climate benefits and risk-adjusted returns through optimal portfolio design.

## Rob

### Exploratory time series analysis using R

Many organisations collect huge amounts of data over time, and we need time series analysis tools capable of handling the scale, frequency and structure of the data collected. In this workshop, we will look at some R packages and methods that have been developed to handle the analysis of large collections of time series. We will look at the tsibble data structure for flexibly managing collections of related time series, and consider how to do data wrangling, data visualisation, and exploratory data analysis to analyse time series data in high dimensions. 